/* autogenerated by Processing revision 1310 on 2025-12-20 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class climate_cuisine_game extends PApplet {


boolean update = false;
boolean gameStarted;
int currentScreen = 0;
boolean click;
/*
 0 = title screen
 1 = order screen
 2 = capture screen
 3 = convert station
 4 = create station
 5 = shop screen
 */

// stats (stuff that changes)
int level = -1; //tut = 0
int carbonCaught;
int totalCarbon = 0;
int carbonConvert;
int totalConvert = 0;
int carbonCreate;
int totalCreate = 0;
int[] materialConverted; // 0 = CO2, 1 = CaCO3
int[] materialCreated;
String[] materialCreatedNames = {
  "Methane",
  "Nanotubes",
  "Alkaseltzer",
  "Concrete",
  "Chalk"
};
/*
 0 = methane
 1 = nanotubes
 2 = alkaseltzer
 3 = concrete
 4 = chalk
 */


// title screen globals
int randomScrollText;
int prevScrollText = 0;
boolean blinky;
String[] scrollText = {
  "Capture the Carbon!", //0
  "Make stuff using Carbon Dioxide!",
  "Do very simple chemistry!",
  "Become a service worker!", //3
  "Learn about the Tech-optimist POV!",
  "Reduce CO2eq from 6343.2 million metric tons!",
  "Most greenhouse gases are produced from transport!", //6
  "Residential/commercial, and the energy it uses, creates 31% of the US's CO2 production",
  "There are two main ways of collecting carbon: precombustion and postcombustion!",
  "You can digitally filter CO2 out of the air!" //9
};

// order screen
int testPerson = 0;
int person1, person2, person3 = 0;
String[] buyers = {
  "Heating Henderson", // for fuel
  "Nanotube Nate", // for nanotubes
  "Alkaseltzer Andy", // for alkaseltzer
  "Building Benny", // for concrete
  "Chalk Coleman", // for chalk
};
String[] buyerReason = {
  "so I can heat buildings and cook", // for fuel
  "so I can do electronics", // for nanotubes
  "so I can have soda", // for alkaseltzer
  "so I can build buildings", // for concrete
  "so I can write on a chalkboard", // for chalk
};


// capture screen
int START_CO2;
int captureRad;
int MOL_SIZE = 10;
int carbonGray = color(128, 128, 128);
int oxygenRed = color(255, 0, 0);
Molecules[] molecule;

// convert screen
Molecules[] convertChamberMols;
boolean[] converting;


// create screen
Reactions[] creation;
/*
methane
 nanotubes
 alkaseltzer
 concrete
 chalk
 */


// shop screen
int shopCO2 = 0; //increase when CO2 amt increase bought
int shopCapture = 0; //increase when capture upgrade bought

public void setup() {
  /* size commented out by preprocessor */;
  background(255);
  frameRate(60);

  carbonCaught = 0;
  carbonConvert = 0;
  carbonCreate = 0;
  captureRad = 67;
  shopCO2 = 0;
  shopCapture = 0;

  randomScrollText = PApplet.parseInt(random(0, scrollText.length));

  materialConverted = new int[2];
  materialConverted[0] = 0;
  materialConverted[1] = 0;

  converting = new boolean[2];
  converting[0] = false;
  converting[1] = false;

  materialCreated = new int[5];
  // println("materialCreated has been created: " + materialCreated);
  person1 = PApplet.parseInt(random(1, buyers.length));
  person2 = PApplet.parseInt(random(1, buyers.length));
  person3 = PApplet.parseInt(random(1, buyers.length));

  while (person2 == person1) {
    person2 = PApplet.parseInt(random(1, buyers.length));
  }
  while (person3 == person1 || person3 == person2) {
    person3 = PApplet.parseInt(random(1, buyers.length));
  }
  println("person setup: " + person1 + person2 + person3);

  START_CO2 = 5;
  molecule = new Molecules[START_CO2];

  for (int i = 0; i < START_CO2; i++) {
    int startX = PApplet.parseInt(random(MOL_SIZE, width - MOL_SIZE));
    int startY = PApplet.parseInt(random(MOL_SIZE, height*0.9f - MOL_SIZE));
    molecule[i] = new Molecules(startX, startY, MOL_SIZE, carbonGray);
  }

  convertChamberMols = new Molecules[5];


  creation = new Reactions[5];

  /*
 0 = fuel C
   1 = C nanotubes C
   2 = alkaseltzer C
   3 = concrete CaCO3
   4 = chalk CaCO3
   */
  creation[0] = new Reactions(width/3, height*0.9f/4, "Methane", 100);
  creation[1] = new Reactions(width/3, 2*height*0.9f/4, "Nanotubes", 100);
  creation[2] = new Reactions(width/3, 3*height*0.9f/4, "Alkaseltzer", 100);
  creation[3] = new Reactions(2*width/3, height*0.9f/4, "Concrete", 100);
  creation[4] = new Reactions(2*width/3, 2*height*0.9f/4, "Chalk", 100);
}

public void draw() {
  //println(currentScreen);
  titleScreen(); // current screen is 0
  orderScreen(); // current screen is 1
  captureScreen(); // current screen is 2
  convertScreen(); // current screen is 3
  createScreen(); // current screen is 4
  shopScreen(); // current screeen is 5
}

public void keyPressed() {
  if (currentScreen == 0) {
    if (key == '1') {
      level = 1;
      currentScreen = 1;
      gameStarted = true;
    }
    if (key == '2') {
      level = 2;
      currentScreen = 1;
      gameStarted = true;
    }
    if (key == '3') {
      level = 3;
      currentScreen = 1;
      gameStarted = true;
    }
  }


  if (gameStarted) {
    if (key == '1') {
      currentScreen = 1;
    }
    if (key == '2') {
      currentScreen = 2;
    }
    if (key == '3') {
      currentScreen = 3;
    }
    if (key == '4') {
      currentScreen = 4;
    }
    if (key == '5') {
      currentScreen = 5;
    }
  }
}

public void mousePressed() {
  click = true;
}

public void mouseReleased() {
  click = false;
}


public void titleScreen() {

  if (currentScreen == 0) {
    background(255);
    titleGameText();
    titleBlinkingText();
    titleScrollingText();
  }
}
public void titleGameText() {
  //displays climate cuisine
  fill(0);
  textAlign(CENTER, CENTER);
  textSize(100);
  text("CLIMATE CUISINE", width/2, height/2 - 150);
}

public void titleBlinkingText() {
  //displays the blinking "press space" to move on to next
  textSize(40);
  if (frameCount % 60 == 0) {
    blinky = !blinky;
  }
  if (blinky) {
    fill(255, 0, 0);
    text ("PRESS 1 for EASY, 2 for MEDIUM, 3 for HARD", width/2, height/2 + 150);
  } else {
    fill(0, 255, 0);
    text ("PRESS 1 for EASY, 2 for MEDIUM, 3 for HARD", width/2, height/2 + 150);
  }
}

public void titleScrollingText() {
  //displays scrolling text
  textAlign(LEFT, CENTER);
  textSize(25);
  fill(0xFF11BAF5);
  if (frameCount % width == 0) {
    randomScrollText = PApplet.parseInt(random(0, scrollText.length));
    println("randomScrollText " + randomScrollText + " has been picked");
    while (randomScrollText == prevScrollText) {
      randomScrollText = PApplet.parseInt(random(0, scrollText.length));
    }
  }
  text(scrollText[randomScrollText], width - (frameCount % width + width/4), height/2);
  prevScrollText = randomScrollText;
}


public void navBar(String screen) {
  // black bar
  fill(0);
  rect(0, 0.9f*height, width, height);
  // white text
  fill(255);
  textSize(25);

  textAlign(CENTER, CENTER);
  text(screen, width/2, 0.95f*height);

  textSize(15);
  textAlign(LEFT, CENTER);
  text("Move screens using the keys [1,2,3,4,5]", width/100, 0.95f*height);

  textSize(12);
  textAlign(RIGHT, CENTER);
  text("Total Captured C: " + totalCarbon + " " + "Total Converted C: " + totalConvert + " " + "Total Created: " +  totalCreate, width-width/100, 0.95f*height);
}

public void statboard(float x, float y) {
  textAlign(CENTER, CENTER);
  fill(0);

  for (int i = 0; i < materialCreated.length; i++) {
    text(materialCreatedNames[i], x-i*75 + 150, y);
    text(materialCreated[i], x-i*75 + 150, y + 15);
  }
}

public void captureScreen() {
  if (currentScreen == 2) {
    background(255);
    navBar("Capture Screen");
    rect(0, height*0.9f-10, width, 10);
    colorMode(HSB, 360, 100, 100);
    fill(frameCount%360, 100, 100);
    rect(0, height*0.9f-10, width-2.5f*(frameCount%300), 10);
    colorMode(RGB, 255, 255, 255);

    captureBackground();
    captureCarbon();

    for (int i = 0; i < molecule.length; i++) {

      molecule[i].move();
      if (molecule[i].visible) {
        molecule[i].display();
      }

      if (frameCount % (60*5) == 0) {
        molecule[i].visible = true;
      }
    }
  }
}

public void captureCarbon() {
  int fullCapture = captureRad + shopCapture*25;
  if (shopCapture != 0) {
    captureRad = 75;
  }
  println(fullCapture);
  strokeWeight(3);
  fill(255, 255, 255, 0);

  circle(mouseX, mouseY, fullCapture);


  for (int i = 0; i < molecule.length; i++) {
    float distanceFromMouse = dist(mouseX, mouseY, molecule[i].position.x, molecule[i].position.y);

    if ((distanceFromMouse <= fullCapture/2) && click) {
      int startX = PApplet.parseInt(random(MOL_SIZE, width - MOL_SIZE));
      int startY = PApplet.parseInt(random(MOL_SIZE, height*0.9f - MOL_SIZE));
      stroke(255, 0, 0);
      if (molecule[i].visible) {
        carbonCaught++;
        totalCarbon++;
      }
      molecule[i].visible = false;
      molecule[i].position = new PVector(startX, startY);
    }
  }

  stroke(0);
  strokeWeight(1);
}

public void captureBackground() {
  fill(255);
  rect(width*0.1f, height*0.1f, width*0.8f, height*0.1f);
  textAlign(CENTER, CENTER);
  textSize(25);
  fill(0);
  text("6343.2 million metric tons of CO2eq in the US (2022)", width/2, height*0.15f);

  fill(255);
  rect(width*0.1f, height*0.2f, width*0.8f, height*0.1f);

  fill(0, 0, 255);
  rect(width*0.1f, height*0.2f, width*0.8f*.28f, height*0.1f);
  fill(255, 255, 0);
  rect(width*0.1f+width*0.8f*.28f, height*0.2f, width*0.8f*.25f, height*0.1f);
  fill(128, 128, 128);
  rect(width*0.1f+width*0.8f*.28f+width*0.8f*.25f, height*0.2f, width*0.8f*.23f, height*0.1f);
  fill(255, 75, 75);
  rect(width*0.1f+width*0.8f*.28f+width*0.8f*.25f+width*0.8f*.23f, height*0.2f, width*0.8f*.13f, height*0.1f);
  fill(0, 255, 0);
  rect(width*0.1f+width*0.8f*.28f+width*0.8f*.25f+width*0.8f*.23f+width*0.8f*.13f, height*0.2f, width*0.8f*.10f, height*0.1f);

  fill(0);
  textSize(15);
  textAlign(LEFT, CENTER);
  text("The Transportation, Electrical, Industrial, Residential/Commercial, and Agricultural sectors", width*0.1f, height*0.35f);
  text("creates 99% of the US's Greenhouse Gases (28%, 25%, 23%, 13%, 10% respectively + 1% other)", width*0.1f, height*0.35f+20);

  textAlign(CENTER, CENTER);
  text("How CO2 becomes usable (as in the playable part):", width/2, height*0.45f);
  textAlign(LEFT, CENTER);
  text("Liquid Filtration", width*0.1f, height*0.485f);
  textAlign(RIGHT, CENTER);
  text("Gas Filtration", width*0.9f, height*0.485f);

  fill(255);
  rect(width*0.1f, height*0.5f, width*0.4f, height*0.25f);
  rect(width*0.1f+width*0.4f, height*0.5f, width*0.4f, height*0.25f);

  textAlign(LEFT, CENTER);
  fill(0);
  text("- extracts CO2 by converting it to CaCO3", width*0.1f+5, height*0.5f+10);
  text("- after CaCO3 is made, needs to heat up to use", width*0.1f+5, height*0.5f+30);
  text("- inefficient", width*0.1f+5, height*0.5f+50);
  text("- takes a while to collect", width*0.1f+5, height*0.5f+70);
  text("CO2+H2O -> H2CO3+Ca(OH)2 -> CaCO3+2H2O", width*0.1f+5, height*0.5f+90);

  text("- extracts CO2 by separating from the air", width*0.5f+5, height*0.5f+10);
  text("- catalysts (end material = starting material)", width*0.5f+5, height*0.5f+30);
  text("- works faster than liquid filtration", width*0.5f+5, height*0.5f+50);
  text("- energy intensive", width*0.5f+5, height*0.5f+70);
  text("CO2(g) -> filter -> CO2(g)", width*0.5f+5, height*0.5f+90);

  textAlign(CENTER, CENTER);
  textSize(20);
  text("Carbon Stored: " + carbonCaught, width/2, height*0.9f - 50);
}

public void convertScreen() {
  if (currentScreen == 3) {
    background(255);
    navBar("Convert Screen");

    rect(0, height*0.9f-10, width, 10);
    colorMode(HSB, 360, 100, 100);
    fill(frameCount%360, 100, 100);
    rect(0, height*0.9f-10, width-2.5f*(frameCount%300), 10);
    colorMode(RGB, 255, 255, 255);

    int flaskRad = 175;
    fill(255);

    convertMech(width/5, height/4, flaskRad, "CO2", 0);
    convertMech(width/5, height*0.9f - height/4, flaskRad, "CaCO3", 1);
    fill(0);
    text(materialConverted[0], width/2, height/4 + 25);
    text(materialConverted[1], width/2, height*0.9f - height/4 + 25);

    textSize(20);

    text("Methane", width-width/5, height/4-25);
    text("Nanotubes", width-width/5, height/4);
    text("Alkaseltzer", width-width/5, height/4+25);

    text("Concrete", width-width/5, height*0.9f - height/4 -15);
    text("Chalk", width-width/5, height*0.9f - height/4 +15);
  }
}

public void convertMech(float x, float y, int flaskRad, String typeName, int type) {

  // chambers
  fill(255);
  rect(x+flaskRad/2, y-10, 3*height/4, 10);
  circle(x, y, flaskRad);
  circle(width-x, y, flaskRad);

  textAlign(CENTER, CENTER);
  textSize(20);
  fill(0);
  text(typeName, width/2, y-25);

  float distance = dist(mouseX, mouseY, x, y);
  if (distance <= flaskRad/2 && click && carbonCaught >= 5) {
    converting[type] = true;
    for (int i = 0; i < convertChamberMols.length; i++) {
      convertChamberMols[i] = new Molecules(PApplet.parseInt(x), PApplet.parseInt(y), MOL_SIZE, carbonGray);
    }
    carbonCaught -= 5;
  }

  if (converting[type] == true) {
    for (int i = 0; i < convertChamberMols.length; i++) {
      convertChamberMols[i].position.x += random(-1, 1);
      convertChamberMols[i].position.y += random(-1, 1);
      convertChamberMols[i].display();
    }
    if (frameCount % 300 == 0) {
      materialConverted[type] += 1;
      totalConvert += 1;
      converting[type] = false;
    }
  }
}

public void createScreen() {
  if (currentScreen == 4) {
    background(255);
    navBar("Create Screen");

    rect(0, height*0.9f-10, width, 10);
    colorMode(HSB, 360, 100, 100);
    fill(frameCount%360, 100, 100);
    rect(0, height*0.9f-10, width-2.5f*(frameCount%300), 10);
    colorMode(RGB, 255, 255, 255);

    fill(0);
    textSize(15);
    textAlign(LEFT, CENTER);
    text("Carbon based: " + materialConverted[0], 5, height*0.9f/2);

    textAlign(RIGHT, CENTER);
    text("Calcium based: " + materialConverted[1], width-5, height*0.9f/2);

    for (int i = 0; i < creation.length; i++) {
      creation[i].display();
      float distanceFromMouse = dist(mouseX, mouseY, creation[i].center.x, creation[i].center.y);

      boolean matConTest = false;
      if (i <= 2) {
        if (materialConverted[0] >= 1) {
          matConTest = true;
        }
      } else {
        if (materialConverted[1] >= 1) {

          matConTest = true;
        }
      }


      if ((distanceFromMouse <= creation[i].chamberRad/2) && click && (matConTest)) {
        creation[i].process = true;
        if (i <= 2) {
          materialConverted[0]--;
        } else {
          materialConverted[1]--;
        }
      }

      if (frameCount % 300 == 0) {
        if (creation[i].process) {
          creation[i].process = !creation[i].process;
          totalCreate++;
          carbonCreate++;
          materialCreated[i] = materialCreated[i] + 1;
        }
      }
    }


    textAlign(CENTER, CENTER);
    textSize(20);
    fill(0);

    text("Press the circles to create your end products!", width/2, 20);

    textSize(15);
    text("Stay on this screen to keep creating the materials", 2*width/3, 3*height*0.9f/4);
    text("There's totally no bugs here", 2*width/3, 3*height*0.9f/4 + 20);
    text("These are your stats:", 2*width/3, 3*height*0.9f/4 + 40);
    statboard(2*width/3, 3*height*0.9f/4 + 60);
  }
}
class Molecules {

  PVector position;
  int radius;
  int carbonColor;
  int movement;
  float randX, randY;
  int molActivity = 5; //smaller # = more jitter
  boolean visible = true;

  Molecules(int x, int y, int r, int c) {
    position = new PVector(x, y);
    radius = r;
    carbonColor = c;
    movement = PApplet.parseInt(random(3, 7));
  }

  public void move() {


    if (frameCount % PApplet.parseInt(random(molActivity, molActivity*2)) == 0) {
      randX = random(-movement, movement);
      randY = random(-movement, movement);
    }
    //println("before randcoords" + randX + " " + randY);

    if (wallCollision(position.x, randX, 1)) {
      randX = randX*-1;
    }
    if (wallCollision(position.y, randY, 2)) {
      randY = randY*-1;
    }

    //println("after randcoords" + randX + " " + randY);
    position.x = position.x + randX;
    position.y = position.y + randY;
  }

  public boolean wallCollision(float mol, float rand, int axis) { // 1 = x, 2 = y

    if (axis == 1) {
      if (mol + rand > width - radius*3 || mol + rand < radius) {
        return true;
      }
    }
    if (axis == 2) {
      if (mol + rand > 0.9f*height - radius || mol + rand < radius) {
        return true;
      }
    }

    return false;
  }

  public void display() {
    fill(carbonColor);
    circle(position.x, position.y, radius);

    fill(255, 0, 0);
    circle(position.x - radius, position.y, radius);
    circle(position.x + radius, position.y, radius);
  }
}
boolean active = true;
boolean replace = false;

int placementX, placementY, newPerson;
public void orderScreen() {
  if (currentScreen == 1) {
    background(255);
    navBar("Order Screen");

    orderTicketAndLevels();
    if (replace) {
      replace(placementX, 0, newPerson);
    }
  }
}

public void orderTicketAndLevels() {
  // println(level);
  if (level == 0) {
    orderTicket(0, 0, width/3, 0.90f*height, testPerson);
  }

  if (level == 1) {
    orderTicket(0, 0, width/3, 0.90f*height, person1);
  }

  if (level == 2) {
    orderTicket(0, 0, width/3, 0.90f*height, person1);
    orderTicket(width/3, 0, width/3, 0.90f*height, person2);
  }

  if (level == 3) {
    orderTicket(0, 0, width/3, 0.90f*height, person1);
    orderTicket(width/3, 0, width/3, 0.90f*height, person2);
    orderTicket(2*width/3, 0, width/3, 0.90f*height, person3);
  }
}

public void orderTicket(float topX, float topY, float ticketWidth, float ticketHeight, int person) {
  fill(255);
  rect(topX, topY, ticketWidth, ticketHeight); //whole ticket

  //ticket head
  rect(topX, topY, ticketWidth, 0.15f*ticketHeight);
  fill(0);
  textSize(25);
  textAlign(CENTER, CENTER);
  text(buyers[person], topX + ticketWidth/2, topY + 0.15f*ticketHeight/2);


  orderChara(PApplet.parseInt(topX+ticketWidth/2), PApplet.parseInt(topY+ticketHeight/2)+50);
  orderBubble(PApplet.parseInt(topX), PApplet.parseInt(topY)+100, PApplet.parseInt(ticketWidth), person);
  orderSend(PApplet.parseInt(topX), PApplet.parseInt(topY)+375, PApplet.parseInt(ticketWidth), person);
}


public void orderChara(int x, int y) {
  fill(255, 0, 0);
  rect(x - 25, y - 50, 50, 100);
  rect(x - 50, y - 25, 25, 50);
  rect(x - 15, y + 50, 15, 25);
  rect(x + 5, y + 50, 15, 25);
  fill(0, 255, 255);
  square(x+10, y-40, 25);
}

public void orderBubble(int x, int y, int w, int type) {
  fill(128);
  rect(x+25, y, w*0.8f, 100);

  fill(0);
  textAlign(CENTER, CENTER);
  textSize(20);
  text("Hey, I want " + materialCreatedNames[type], x+25 + w*0.4f, y+50);
  textSize(15);
  text(buyerReason[type], x+25 + w*0.4f, y+75);

  if (type == 4) {
    textAlign(LEFT, CENTER);
    textSize(10);
    text("Sorry I didn't have any short sentences for uses of chalk", x + 10, y+110);
  }
}

public void orderSend(int x, int y, int w, int type) {
  fill(0xFF1B17BC);
  rect(x+25, y, w*0.8f, 50, 10);

  fill(255);
  textAlign(CENTER, CENTER);
  textSize(20);
  text("Send me " + materialCreatedNames[type], x+25 + w*0.4f, y+20);

  if (materialCreated[type] >= 1 && active && click && withinBorder(x+25, y, x+25+PApplet.parseInt(w*0.8f), y+50)) {
    int prevPerson = type;
    int person = PApplet.parseInt(random(1, buyers.length));

    while (person == prevPerson) {
      person = PApplet.parseInt(random(1, buyers.length));
    }
    replace = true;
    placementX = x;
    placementY = y;
    newPerson = person;
    
    materialCreated[type]--;
  }
}

public boolean withinBorder(int tx, int ty, int bx, int by) {
  if (mouseX >= tx && mouseX <= bx) {
    if (mouseY >= ty && mouseY <= by) {
      return true;
    }
  }
  return false;
}

public void replace(int x, int y, int person) {
  if (replace) {
    orderTicket(x, y, width/3, 0.9f*height, person);
    
  }
}

class Reactions {
  PVector center;
  String type;
  int chamberRad;
  boolean process;
  int count = 0;


  Reactions(float x, float y, String t, int r) {
    center = new PVector(x, y);
    type = t;
    chamberRad = r;
  }

  public void display() {
    fill(255);
    circle(center.x, center.y, chamberRad);
    fill(0);
    textSize(12.5f);

    if (center.x < width/2) {
      textAlign(RIGHT, CENTER);
      text(type + ": " + count, center.x - chamberRad/2 - 5, center.y);
    }
    if (center.x > width/2) {
      textAlign(LEFT, CENTER);
      text(type + ": " + count, center.x + chamberRad/2 + 5, center.y);
    }

    if (process) {
      colorMode(HSB, 360, 100, 100);
      fill(frameCount%360, 100, 100);
      circle(center.x, center.y, chamberRad);
      colorMode(RGB, 255, 255, 255);
    }
  }
}

public void shopScreen() {
  if (currentScreen == 5) {
    background(255);
    navBar("Shop Screen");

    shopButton(width/3, height*0.9f/2, 200, "Amount of CO2 available", 0, 10);
    shopButton(2*width/3, height*0.9f/2, 200, "Size of CO2 capture radius", 1, 5);

    text(shopCO2 + " out of 5", width/3, height*0.9f - 100);
    text(shopCapture + " out of 5", 2*width/3, height*0.9f - 100);
  }
}

public void shopButton(float x, float y, int r, String typeName, int type, int cost) {
  fill(255);
  circle(x, y, r);

  textAlign(CENTER, CENTER);
  textSize(20);
  fill(0);
  text(typeName, x, y - r/2 - 15);

  float distanceFromMouse = dist(mouseX, mouseY, x, y);

  if (distanceFromMouse <= r/2 && click) {
    if (carbonCreate >= cost) {
      fill(0);
      circle(x, y, r);

      if (type == 0) {
        if (shopCO2 != 5) {
          molecule = (Molecules[])expand(molecule);
          shopCO2++;

          for (int i = 0; i < molecule.length; i++) {
            int startX = PApplet.parseInt(random(MOL_SIZE, width - MOL_SIZE));
            int startY = PApplet.parseInt(random(MOL_SIZE, height*0.9f - MOL_SIZE));
            molecule[i] = new Molecules(startX, startY, MOL_SIZE, carbonGray);
          }
        }
      }

      if (type == 1) {
        if (shopCapture != 5) {
          shopCapture++;
        }
      }

      carbonCreate-=cost;
    }
  }
}


  public void settings() { size(750, 500); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "climate_cuisine_game" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
